### Hyperparameters
NEURONS: 10
GENERATIONS: 200
INDIVIDUALS: 500
PARENTS_MATING: 5
PARENT_SELECTION: "sss"
CROSSOVER_TYPE: "single_point"
CROSSOVER_PROB: null
MUTATION_TYPE:  "random"
MUTATION_PERCENT: 10



### Run settings
DATASET_NUMBER: null
DATA_FILE: "manual_dataset"
SIM_TIME: 13            # max 40 secs
NUMBER_PROCESSES: 10
WANDB_LOG:          True
SHOW_PLOTS:         True
SAVE_LAST_SOLUTION: True
IZHIK_TIME_STEP: 0.02


### Dataset parameters
DATASET_DIR: "Sim_data/derivative"
INPUT_COLUMN_DATAFILE: [1]
LABEL_COLUMN_DATAFILE: [1]

### Init settings
RANDOM_INIT_SEED: 1
INIT_SETTING: "random"
HALF_NEGATIVE_WEIGHTS: True

##############################################
# Want to keep params const:
#   - Set the intial conditions to that value
#   - Same for the parameter bounds


############# Initial conditions #############
INITIAL_PARAMS_RANDOM:
# First layer
 a:         [0.019,        0.021]
 b:         [0.1,         0.35]
 c:         [-56,         -54]
 d:         [0,            1]
 threshold: [30,           30]
 v2:        [0.1,          0.15]
 v1:        [7,            7.5]
 v0:        [42,           48]
 tau_u:     [4,            6]
 weights_1:  [50,           100]

# Second layer
 leak:      [0.90,         0.90]
 weights_2: [0.15,         0.15]



#############  Parameter bounds #############
# no constrains --> null
# constraints --> {"low": 0,"high": 0.2, "step":0.01}   step is optional
# not trained --> set to float/int
PARAMETER_BOUNDS: #null if None in python
# First layer
  l1.neuron.a:  {"low": 0,"high": 0.2}
  l1.neuron.b:  {"low": 0,"high": 0.35}
  l1.neuron.c:  {"low": -100,"high": 0}
  l1.neuron.d:  {"low": 0,"high": 10}
  l1.neuron.v2: {"low": 0,"high": 0.5}
  l1.neuron.v1: {"low": 0,"high": 9}
  l1.neuron.v0: {"low": 0,"high": 200}
  l1.neuron.tau_u: {"low": 0,"high": 100}
  l1.neuron.thresh: {"low": 0,"high": 30}
  l1.ff.weight: {"low": -200,"high": 200}  #also negative!

# Second layer
  l2.neuron.leak: 0.9
  l2.ff.weight:   {"low": -0.25,"high": 0.25} #also negative!


