### Hyperparameters
NEURONS: 10
GENERATIONS: 250
INDIVIDUALS: 500
PARENTS_MATING: 2
DATASET_NUMBER: null
DATA_FILE: "manual_dataset"
SIM_TIME: 13            # max 40 secs
NUMBER_PROCESSES: 10
LABEL_COLUMN_DATAFILE: [2]
IZHIK_TIME_STEP: 0.1
HALF_NEGATIVE_WEIGHTS: True


PARENT_SELECTION: "sss"
CROSSOVER_TYPE: "single_point"
CROSSOVER_PROB: 0.4
MUTATION_TYPE:  "adapt_step_size"  #adapt_step_size is the self made, requires all bound to be defined by low and up only!
MUTATION_PERCENT: 20


### Run settings
WANDB_LOG:          True
SHOW_PLOTS:         True
SAVE_LAST_SOLUTION: True


### Dataset parameters
DATASET_DIR: "Sim_data/derivative"
INPUT_COLUMN_DATAFILE: [1]


### Init settings
RANDOM_INIT_SEED: 1
INIT_SETTING: "random"


##############################################
# Want to keep params const:
#   - Set the intial conditions to that value
#   - Same for the parameter bounds


############# Initial conditions #############
INITIAL_PARAMS_RANDOM:
# First layer
 a:         [0.06,        0.07]
 b:         [0.19,         0.21]
 c:         [-10,         0]
 d:         [0.09,        0.11]
 threshold: [0,           10]
 v2:        [0.004,          0.3]
 v1:        [3.5,            6.5]
 v0:        [110,           120]
 tau_u:     [20,            60]
 weights_1:  [180,           200]

# Second layer
 leak:      [0.90,         0.90]
 weights_2: [0.15,         0.20]



#############  Parameter bounds #############
# no constrains --> null
# constraints --> {"low": 0,"high": 0.2, "step":0.01}   step is optional
# not trained --> set to float/int
PARAMETER_BOUNDS: #null if None in python
# First layer
  l1.neuron.a:  {"low": 0,"high": 0.2}
  l1.neuron.b:  {"low": 0.1,"high": 0.6}
  l1.neuron.c:  {"low": -50,"high": 0}
  l1.neuron.d:  {"low": 0,"high": 1}
  l1.neuron.v2: {"low": 0.03,"high": 0.9}
  l1.neuron.v1: {"low": 2,"high": 10}
  l1.neuron.v0: {"low": 30,"high": 300}
  l1.neuron.tau_u: {"low": 0,"high": 100}
  l1.neuron.thresh: {"low": 0,"high": 20}
  l1.ff.weight: {"low": -200,"high": 200}  #also negative!

# Second layer
  l2.neuron.leak: {"low": 0.9,"high": 0.9}
  l2.ff.weight:   {"low": -0.25,"high": 0.25} #also negative!


