ALGORITHM: pycma
ALTERNATIVE_INPUT_COLUMN:
- 3
ALTERNATIVE_TARGET_COLUMN:
- 6
ANTI_OVERFITTING: true
BOUNDS_W1_H2_NEG: false
BOUND_LEAKI_HALF_ZERO: false
BOUND_W2_Q2_Q4_NEG: false
CUSTOM:
  l1.ff.bias: range
  l1.ff.weight: range
  l1.neuron.leak_i: manual
  l1.neuron.leak_v: gaussian
  l1.neuron.thresh: range
  l1.rec.weight: range
  l2.ff.weight: range
  l2.neuron.leak: range
DATASET_DIR: Sim_data/blimp/neutral_seperate_os2/datasets
DATASET_NUMBER: null
DIFFERENT_DATASET_EVERY_GENERATION: 1
DZ_INITIAL: 0
FITNESS_FUNCTION: mae+p
GENERATIONS: 80000
INDIVIDUALS: 80
INIT_LEAKI_HALF_ZERO: false
INIT_W1_H2_NEG: false
INIT_W2_Q2_Q4_NEG: false
LAYER_SETTING:
  l0:
    bias: true
    enabled: true
    neurons: 40
    shared_leak_iv: true
    shared_thres: true
    shared_weight_and_bias: true
  l1:
    adapt_2x2_connection: true
    adapt_share_add_t: true
    adapt_share_baseleak_t: true
    adapt_thres_input_spikes: true
    adaptive: true
    bias: false
    recurrent: true
    shared_2x2_weight_cross: false
    shared_leak_iv: false
    shared_weight_and_bias: false
    w_diagonal: true
    w_diagonal_2x2: true
  l2:
    complementary_leak: true
    shared_weight_and_bias: true
MEAN_SETTING: same for all
NEURONS: 40
NUMBER_PROCESSES: 20
PARAMETER_BOUNDS:
  l0.ff.bias:
    high: 1
    low: -1
  l0.ff.weight:
    high: 1.5
    low: -1.5
  l0.neuron.leak_i:
    high: 0.99
    low: 0
  l0.neuron.leak_v:
    high: 1
    low: 0
  l0.neuron.thresh:
    high: 10
    low: 0.8
  l1.ff.bias:
    high: 1
    low: -1
  l1.ff.weight:
    high: 1.5
    low: -1.5
  l1.neuron.add_t:
    high: 1
    low: -1
  l1.neuron.base_t:
    high: 2
    low: 0
  l1.neuron.leak_i:
    high: 0.99
    low: 0
  l1.neuron.leak_t:
    high: 0.99
    low: 0
  l1.neuron.leak_v:
    high: 1
    low: 0
  l1.neuron.thresh:
    high: 10
    low: 0.8
  l1.rec.weight:
    high: 0.2
    low: -0.2
  l2.ff.weight:
    high: 1.0
    low: -1.0
  l2.neuron.leak:
    high: 0.6
    low: 0.15
PERCENT_INTIIAL_STEPSIZE: 0.005
PREVIOUS_SOLUTION: 38-smart-blaze
SAME_FOR_ALL: range
SAVE_LAST_SOLUTION: true
SAVE_TEST_SOLUTION_STEPSIZE: 50
SHOW_PLOTS: false
SIM_TIME: 115
START_DATASETS_IN_MIDDLE: false
TARGET_FITNESS: 1
TEST_DATA_FILE: test_dataset
TEST_SIM_TIME: 700
TIME_STEP: 0.1
WANDB_LOG: true
Z_INITIAL: 0
gaussian:
  l1.ff.bias: 0.5
  l1.ff.weight: 1
  l1.neuron.leak_i: 0.9
  l1.neuron.leak_v: 0.9
  l1.neuron.thresh: 1
  l1.rec.weight: 0.001
  l2.ff.weight: 0.2
  l2.neuron.leak: 0.9
range:
  l0.ff.bias:
  - 0.2
  - 0.5
  l0.ff.weight:
  - 1
  - 1.5
  l0.neuron.leak_i:
  - 0.1
  - 0.9
  l0.neuron.leak_v:
  - 0.1
  - 0.9
  l0.neuron.thresh:
  - 0.8
  - 1.2
  l1.ff.bias:
  - 0.2
  - 0.5
  l1.ff.weight:
  - 1
  - 1.5
  l1.neuron.add_t:
  - 0.01
  - 0.3
  l1.neuron.base_t:
  - 1
  - 2
  l1.neuron.leak_i:
  - 0.1
  - 0.9
  l1.neuron.leak_t:
  - 0.1
  - 0.9
  l1.neuron.leak_v:
  - 0.1
  - 0.9
  l1.neuron.thresh:
  - 0.8
  - 1.2
  l1.rec.weight:
  - 0.001
  - 0.002
  l2.ff.weight:
  - 0.4
  - 0.5
  l2.neuron.leak:
  - 0.249
  - 0.35
